# Generated by Django 4.2 on 2025-11-13 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("total_equipment", models.IntegerField(default=0)),
                ("avg_flowrate", models.FloatField(default=0)),
                ("avg_pressure", models.FloatField(default=0)),
                ("avg_temperature", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_name", models.CharField(max_length=255)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("Centrifugal Pump", "Centrifugal Pump"),
                            ("Heat Exchanger", "Heat Exchanger"),
                            ("Rotary Compressor", "Rotary Compressor"),
                            ("Particulate Filter", "Particulate Filter"),
                            ("Batch Reactor", "Batch Reactor"),
                            ("Distillation Column", "Distillation Column"),
                            ("Gear Pump", "Gear Pump"),
                            ("Bag Filter", "Bag Filter"),
                            ("Crystallizer", "Crystallizer"),
                            ("Wet Scrubber", "Wet Scrubber"),
                            ("Centrifuge", "Centrifuge"),
                            ("Continuous Reactor", "Continuous Reactor"),
                        ],
                        max_length=100,
                    ),
                ),
                ("flowrate", models.FloatField()),
                ("pressure", models.FloatField()),
                ("temperature", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="equipment_api.uploadbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["equipment_name"],
            },
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["batch", "equipment_type"],
                name="equipment_a_batch_i_e828fa_idx",
            ),
        ),
    ]
